---
- name: Download jdk linux
  become: true
  get_url: url="https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.rpm" dest="/tmp/jdk-19_linux-x64_bin.rpm" owner=root group=root
  when: ansible_os_family == "Linux"
  tags: descarga

- name: Install with rpm
  become: true
  yum:
    name: /tmp/jdk-19_linux-x64_bin.rpm
    state: present
  
- name: Download jdk windows
  win_get_url:
    url: https://download.oracle.com/java/19/latest/jdk-19_windows-x64_bin.msi
    dest: C:\weblogic-dependencies
    validate_certs: no
  #when: java_version['failed'] == true
  when: ansible_os_family == "Windows"

- name: Install weblogic windows
  shell: "msi path_jdk"


- name: Uninstall jdk
  shell: rpm -e jdk-19_linux-x64_bin.rpm
  tags: uninstall