# ==> Configure Linux
- name: Install required libraries
  yum: name={{ item }} state=present
  with_items: '{{ packages_list }}'
- name: Disable SELinux
  selinux: state=disabled
- name: Disable Firewall Deamon (firewalld)
  service: name=firewalld state=stopped enabled=no
- name: Change kernel parameters
  sysctl: name="{{ item.key }}" value="{{ item.value }}" state=present
  with_dict: '{{ kernel_params }}'

# ==> Create user and groups
- name: Create groups
  group: name={{ oracle_group }} state=present
- name: Create user
  user: name={{ oracle_user }} groups={{ oracle_group }} password={{ oracle_os_user_pass }}
  
# ==> Add open file and process limits for oracle user
- name: Create a shell profile with file and process limits for oracle user
  template: src=oracle-limits.sh dest=/etc/profile.d/

# ==> Add limits for oracle user
- name: Add oracle user limits
  lineinfile: dest=/etc/security/limits.conf line='{{ oracle_user }} {{ item.limit }} {{ item.type}} {{ item.value }}'
  with_items:
    - { limit: 'soft', type: nofile, value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: nofile, value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: nproc, value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: nproc, value: '{{ hard_nproc }}' }

# ==> Create Base Directories
- name: Create Oracle Home directory
  file: state=directory path={{ middleware_home }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Crear jdk_folder
  file: state=directory path={{ jdk_folder }} owner={{ oracle_user }} group={{ oracle_group }}

- name: Change ownership of jdk folder
  file: path="{{ jdk_folder }}" owner={{ oracle_user }} group={{ oracle_group }} recurse=yes
 
- name: Download jdk linux
  become: true
  get_url: url="https://{{ server }}/s/qAzgiitjSTybGY8/download/jdk-8u202-linux-x64.rpm" dest="/{{ jdk_folder }}/jdk-8u202-linux-x64.rpm" owner={{ oracle_user }} group={{ oracle_group }} validate_certs=no
  #when: ansible_os_family == "Linux"
  tags: descarga

- name: Install with rpm
  become: true
  yum:
    name: /{{ jdk_folder }}/jdk-19_linux-x64_bin.rpm
    state: present