---
# tasks file for linux-jdk
- name: Download jdk
  get_url: url="https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.tar.gz" dest="/etc/jdk-19_linux-x64_bin.tar.gz"
  #when: mysql_apt_config_check_deb.rc == 1